version: '3'
services:
  order-service:
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
#    container_name: order
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
#    container_name: order-db