// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DistanceCalculator is an autogenerated mock type for the DistanceCalculator type
type DistanceCalculator struct {
	mock.Mock
}

// GetDistance provides a mock function with given fields: origins, destinations
func (_m *DistanceCalculator) GetDistance(origins []string, destinations []string) (int, error) {
	ret := _m.Called(origins, destinations)

	var r0 int
	if rf, ok := ret.Get(0).(func([]string, []string) int); ok {
		r0 = rf(origins, destinations)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, []string) error); ok {
		r1 = rf(origins, destinations)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
